highlighter: rouge
markdown: kramdown 
kramdown:
  input:         GFM
  syntax_highlighter: rouge
  auto_ids:      true


# 作者信息
author: 欧阳湘粤
name: Owen
email: 469564715@qq.com
link: http://numerhero.github.io
#weibo: 
github: http://github.com/NumerHero

# 站点信息
title: Owen的博客 
description: 欧阳湘粤的博客
url: http://numerhero.github.io
rss_url: /pages/atom.xml

# disqus 设置
disqus:
  shortname: owen

# duoshuo 设置
